#!/bin/bash

# Function to install packages
install_packages() {
    PACKAGE_MANAGER=$1
    shift
    PACKAGES="$@"

    case $PACKAGE_MANAGER in
        apt)
        	echo "Installing required packages..."
            sudo apt update &> /dev/null
            sudo apt install -y $PACKAGES &> /dev/null
            ;;
        dnf)
        	echo "Installing required packages..."
            sudo dnf install -y $PACKAGES &> /dev/null
            ;;
        yum)
        	echo "Installing required packages..."
            sudo yum install -y $PACKAGES &> /dev/null
            ;;
        pacman)
        	echo "Installing required packages..."
            sudo pacman -Syu --noconfirm $PACKAGES &> /dev/null
            ;;
        zypper)
        	echo "Installing required packages..."
            sudo zypper install -y $PACKAGES &> /dev/null
            ;;
        apk)
        	echo "Installing required packages..."
            sudo apk add $PACKAGES &> /dev/null
            ;;
        *)
            echo "Unsupported package manager: $PACKAGE_MANAGER"
            exit 1
            ;;
    esac
}

# Detect package manager
if command -v apt &> /dev/null; then
    install_packages apt git curl
elif command -v dnf &> /dev/null; then
    install_packages dnf git curl
elif command -v yum &> /dev/null; then
    install_packages yum git curl
elif command -v pacman &> /dev/null; then
    install_packages pacman git curl
elif command -v zypper &> /dev/null; then
    install_packages zypper git curl
elif command -v apk &> /dev/null; then
    install_packages apk git curl
else
    echo "No supported package manager found."
    exit 1
fi

echo "Required packages have been installed successfully."
echo "Cloning F1ND3R..."
git clone https://github.com/WhizBytes/f1nd3r.git &> /dev/null
cd f1nd3r
chmod +x f1nd3r.x
echo "Starting F1ND3R..."
sleep 3
clear
./f1nd3r.x
